### ISSUE TITLE
How to install Vorwerk homebridge plugin with Hass.io

### ISSUE THREAD

**Issue by carloleocosta** [nicoh88/homebridge-vorwerk#4]
Hallo,
I'm using Home Assistant 0.77.3 Hass.io version.
I've installed the Homebridge Hassio add-on 2.8.1. Now I'm wondering how to "Install this plugin using: npm install -g homebridge-vorwerk" since, as far as I know, with Hass.io I'm not able to execute such commands. Can you help me? I'm really curious to test and use your fantastic VR200 Home Assistant interface :)
Thanks a lot for your help.
Carlo

**Comment by nicoh88** [comment]
Sorry, I dont know. Please, ask in the Hass.io community.
